name: CD

on:
  workflow_run:
    pull_request:
      branches: [ "develop" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      input:
        description: 'Version to deploy'
        required: true
        default: '1.0.1'

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name : Deploy
      run: |
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
        echo "Deployed version: ${{ github.event.inputs.input }}"
        docker pull juromerop/to-do-app:${{ github.event.inputs.input }}
        docker run -d -p 3000:3000 juromerop/to-do-app:${{ github.event.inputs.input }}