name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name : Deploy
      run: |
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
        echo "Deployed version: $(cat ./app/version.txt)"
        docker pull juromerop/to-do-app:$(cat ./app/version.txt)
        docker run -d -p 3000:3000 juromerop/to-do-app:$(cat ./app/version.txt)
  
  delivery:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Delivery
      run: |
        echo "Delivered version: $(cat ./app/version.txt)"