name: CDV

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add build and test steps here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Manual Approval
        if: github.event_name == 'workflow_dispatch'
        run: echo "Please approve the deployment in the GitHub UI"

      - name: Deploy to Production
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'build'
        run: |
          # Add your deployment steps here
          echo "Deploying to production"