name: CDV

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Manual Approval
        uses: "peter-evans/approval-action@v2"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Approve deployment to production"
          reviewers: "juromerop"

      - name: Deploy to Production
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        run: |
          echo "Deploying to production"