name: CDV

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Manual Approval
      if: github.event.workflow_run.conclusion == 'success'
      run: |
        TAG_NAME=$(cat ./app/version.txt)
        echo "Creating new GitHub release for tag $TAG_NAME..."
        gh release create $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}