name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t v:1.0.0 ./app

    - name: Test
      run: docker run v:1.0.0 npm test
