name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    # env:
    #   IMAGE_VERSION: "1.1.1"

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t juromerop/to-do-app ./app

    - name: Test
      run: docker run juromerop/to-do-app npm test

    # - name: Tag
    #   run: |
    #     echo "${IMAGE_VERSION}" > ./app/version.txt
    #     docker tag juromerop/to-do-app juromerop/to-do-app:${IMAGE_VERSION}
      
    # - name: Push
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u juromerop --password-stdin
    #     docker push juromerop/to-do-app:${IMAGE_VERSION}

    - name: Tag
      run: |
        echo ${{ github.run_id }} > ./app/version.txt
        docker tag juromerop/to-do-app juromerop/to-do-app:${{ github.run_id }}
      
    - name: Push
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u juromerop --password-stdin
        docker push juromerop/to-do-app:${{ github.run_id }}