name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t juromerop/to-do-app ./app

    - name: Test
      run: docker run juromerop/to-do-app npm test

    # - name: Tag
    #   run: |
    #     echo ${{ github.sha }} > ./app/version.txt
    #     docker tag juromerop/to-do-app juromerop/to-do-app:${{ github.sha }}

    - name: Tag
      run: |
        commit_message=$(git log -1 --pretty=%B)
        version=$(echo "${commit_message}" | grep -oP '(?<=version: ).*')
        if [ -z "${version}" ]; then
          version="1.0.0"
        fi
        echo "${version}" > ./app/version.txt
        docker tag juromerop/to-do-app juromerop/to-do-app:${version}

      
    - name: Push
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u juromerop --password-stdin
        docker push juromerop/to-do-app:${version}