name: CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v3

    - name: Build
      run: docker build -t juromerop/to-do-app ./app

  test:

    runs-on: self-hosted

    needs: build

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Test
      run: docker run juromerop/to-do-app npm test
  
  release:

    runs-on: self-hosted

    needs: test

    steps:
    - name: Tag
      run: |
        docker tag juromerop/to-do-app juromerop/to-do-app:$(cat ./app/version.txt)
      
    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push juromerop/to-do-app:$(cat ./app/version.txt)