name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t juromerop/to-do-app ./app

    - name: Test
      run: docker run juromerop/to-do-app npm test

    - name: Tag
      run: |
        echo ${{ github.sha }} > ./app/version.txt
        docker tag juromerop/to-do-app juromerop/to-do-app:${{ github.sha }}